// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package indexdb

type Chunk struct {
	Key          string
	DocumentPath string
	LineNumber   int64
	Content      string
}

type Document struct {
	Path     string
	Ext      string
	Modified int64
}

type Posting struct {
	Term     string
	ChunkKey string
	Tf       int64
}
