// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package indexdb

import (
	"context"
	"database/sql"
	"strings"
)

const clearChunks = `-- name: ClearChunks :exec
DELETE FROM chunks
`

func (q *Queries) ClearChunks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearChunks)
	return err
}

const clearDocuments = `-- name: ClearDocuments :exec
DELETE FROM documents
`

func (q *Queries) ClearDocuments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDocuments)
	return err
}

const clearPostings = `-- name: ClearPostings :exec
DELETE FROM postings
`

func (q *Queries) ClearPostings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearPostings)
	return err
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO chunks(key, document_path, line_number, content)
VALUES (?, ?, ?, ?)
`

type CreateChunkParams struct {
	Key          string
	DocumentPath string
	LineNumber   int64
	Content      string
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.ExecContext(ctx, createChunk,
		arg.Key,
		arg.DocumentPath,
		arg.LineNumber,
		arg.Content,
	)
	return err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents(path, ext, modified)
VALUES (?, ?, ?)
`

type CreateDocumentParams struct {
	Path     string
	Ext      string
	Modified int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument, arg.Path, arg.Ext, arg.Modified)
	return err
}

const createPosting = `-- name: CreatePosting :exec
INSERT INTO postings(term, chunk_key, tf)
VALUES (?, ?, ?)
`

type CreatePostingParams struct {
	Term     string
	ChunkKey string
	Tf       int64
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) error {
	_, err := q.db.ExecContext(ctx, createPosting, arg.Term, arg.ChunkKey, arg.Tf)
	return err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE path = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, path)
	return err
}

const listChunks = `-- name: ListChunks :many
SELECT key, document_path, line_number, content
FROM chunks
`

func (q *Queries) ListChunks(ctx context.Context) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, listChunks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.Key,
			&i.DocumentPath,
			&i.LineNumber,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT path, ext, modified
FROM documents
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(&i.Path, &i.Ext, &i.Modified); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostings = `-- name: ListPostings :many
SELECT term, chunk_key, tf
FROM postings
`

func (q *Queries) ListPostings(ctx context.Context) ([]Posting, error) {
	rows, err := q.db.QueryContext(ctx, listPostings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(&i.Term, &i.ChunkKey, &i.Tf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByTerms = `-- name: SearchByTerms :many
SELECT
  c.key,
  c.document_path,
  c.line_number,
  c.content,
  d.path,
  d.ext,
  d.modified,
  SUM(p.tf) AS score
FROM postings p
JOIN chunks c ON c.key = p.chunk_key
JOIN documents d ON d.path = c.document_path
WHERE p.term IN (/*SLICE:terms*/?)
GROUP BY c.key, c.document_path, c.line_number, c.content, d.path, d.ext, d.modified
ORDER BY score DESC, d.path ASC, c.line_number ASC
LIMIT ?
`

type SearchByTermsParams struct {
	Terms []string
	Limit int64
}

type SearchByTermsRow struct {
	Key          string
	DocumentPath string
	LineNumber   int64
	Content      string
	Path         string
	Ext          string
	Modified     int64
	Score        sql.NullFloat64
}

func (q *Queries) SearchByTerms(ctx context.Context, arg SearchByTermsParams) ([]SearchByTermsRow, error) {
	query := searchByTerms
	var queryParams []interface{}
	if len(arg.Terms) > 0 {
		for _, v := range arg.Terms {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terms*/?", strings.Repeat(",?", len(arg.Terms))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terms*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByTermsRow
	for rows.Next() {
		var i SearchByTermsRow
		if err := rows.Scan(
			&i.Key,
			&i.DocumentPath,
			&i.LineNumber,
			&i.Content,
			&i.Path,
			&i.Ext,
			&i.Modified,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByTermsAndExts = `-- name: SearchByTermsAndExts :many
SELECT
  c.key,
  c.document_path,
  c.line_number,
  c.content,
  d.path,
  d.ext,
  d.modified,
  SUM(p.tf) AS score
FROM postings p
JOIN chunks c ON c.key = p.chunk_key
JOIN documents d ON d.path = c.document_path
WHERE p.term IN (/*SLICE:terms*/?)
  AND d.ext IN (/*SLICE:exts*/?)
GROUP BY c.key, c.document_path, c.line_number, c.content, d.path, d.ext, d.modified
ORDER BY score DESC, d.path ASC, c.line_number ASC
LIMIT ?
`

type SearchByTermsAndExtsParams struct {
	Terms []string
	Exts  []string
	Limit int64
}

type SearchByTermsAndExtsRow struct {
	Key          string
	DocumentPath string
	LineNumber   int64
	Content      string
	Path         string
	Ext          string
	Modified     int64
	Score        sql.NullFloat64
}

func (q *Queries) SearchByTermsAndExts(ctx context.Context, arg SearchByTermsAndExtsParams) ([]SearchByTermsAndExtsRow, error) {
	query := searchByTermsAndExts
	var queryParams []interface{}
	if len(arg.Terms) > 0 {
		for _, v := range arg.Terms {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terms*/?", strings.Repeat(",?", len(arg.Terms))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terms*/?", "NULL", 1)
	}
	if len(arg.Exts) > 0 {
		for _, v := range arg.Exts {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exts*/?", strings.Repeat(",?", len(arg.Exts))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exts*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByTermsAndExtsRow
	for rows.Next() {
		var i SearchByTermsAndExtsRow
		if err := rows.Scan(
			&i.Key,
			&i.DocumentPath,
			&i.LineNumber,
			&i.Content,
			&i.Path,
			&i.Ext,
			&i.Modified,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
